print("             THE FUTURISTIC SPORTS BATTLE                        ")
print("                                                                 ")
print("          ///////                    /////                       ")
print("         ---------                 ---------                     ")
print("         | () () |                 | x   x |                     ")
print("         |   >   |                 |   <   |                     ")
print("         |  -o-  |                 |  -o-  |                     ")
print("         ---------                 ---------                     ")
print("   o=====| NIKE$ |=====o     o=====|ADIDAS€|=====o               ")
print("         |   -   |                 |   -   |                     ")
print("         |e-sport|                 |e-sport|                     ")
print("         ---------                 ---------                     ")
print("         |       |                 |       |                     ")
print("         |       |                 |       |                     ")
print("       <=|       |=>   (=)       <=|       |=>                   ")
print(" _________________________________________________________       ")
